AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  UploadBucketName:
    Type: String

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucketName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /presign
            Method: post

Outputs:
  PresignApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/presign"
